services:
  backend:
    container_name: mocksewa-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # Exposes the backend API
    volumes:
      - ./backend:/app # Syncs local backend directory with the container
    depends_on:
      - redis
    networks:
      - app-network # Ensure the backend is on the app-network

  redis:
    image: redis:latest
    container_name: mocksewa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network # Ensure Redis is on the app-network

networks:
  app-network:
    driver: bridge # Uses the bridge driver to create the network

volumes:
  postgres_data:
  redis_data:
