services:
  backend:
    volumes:
      - ./backend:/app
    command: ["yarn", "dev"] # This brings back hot-reload locally!
  db:
    image: postgres:15
    container_name: mocksewa-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Set the database user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Set the database password
      POSTGRES_DB: ${POSTGRES_DB} # Set the database name
    ports:
      - "5433:5432" # Exposes the database on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
