name: CI/CD Backend Deployment

on:
  push:
    branches:
      - main # Change this to 'master' if that is your primary branch
  workflow_dispatch: # Allows you to trigger it manually from the UI

jobs:
  deploy:
    name: Build and Deploy on Azure VM
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            cd mock-sewa-backend/
            git pull origin main
            docker compose up -d --build --remove-orphans
            docker image prune -f
